version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn -w 5 --bind 0.0.0.0:80 run
    ports:
      - '80:80'
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python3 tgbot.py